### PR TITLE
add husl requirement

### PR DESCRIPTION
**Pull request by mcsalgado**

### CODE REVIEW

**Comment by JanSchulz** [comment]
Can you provide an explanation why this change is needed?

**Comment by mcsalgado** [comment]
I can't "pip install ggplot" and immediately import ggplot to use it without installing husl first. I get "ImportError: No module named 'husl'".

**Comment by psychemedia** [comment]
See https://github.com/yhat/ggplot/pull/369

Has the location of the husl.py file been changed?

**Comment by haleemur** [comment]
After I installed ggplot in a fresh virtual environment on python 3.4.3 using the command

    pip install ggplot

I faced the same issue as documented by @mcsalgado.

For new users, this might be confusing to have to read a traceback and figure out to install husl as well. The issue can be wholly avoided if we add husl to setup.py as a requirement. *its already specified in travis.yml as a dependency*

**Pull request closed without merging**
